export const favoritesTypes = {
	ADD_FAV: 'ADD_FAV',
	REMOVE_FAV: 'REMOVE_FAV',
	FILTER: 'FILTER',
	ORDER: 'ORDER',
	CLEAR_FAV: 'CLEAR_FAV',
}

export const charactersTypes = {
	ADD_CHARACTER: 'ADD_CHARACTER',
	DELETE_CHARACTER: 'DELETE_CHARACTER',
	FETCH_DETAIL_REQUEST: 'FETCH_DETAIL_REQUEST',
	FETCH_DETAIL_SUCCESS: 'FETCH_DETAIL_SUCCESS',
}
